# Site settings
author: Kaela Clement
title: Unexpected Input
header-img: img/home-bg.png
email: stephanie.kaela@gmail.com
copyright_name: Kaela Clement
description: > # this means to ignore newlines until "baseurl:"
  Learning one error at a time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kaelaclement

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
